// <auto-generated />
namespace HackAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class carts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(carts));
        
        string IMigrationMetadata.Id
        {
            get { return "201504112210524_carts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
