// <auto-generated />
namespace HackAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class removecard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removecard));
        
        string IMigrationMetadata.Id
        {
            get { return "201504120441165_removecard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
